openapi: 3.0.0
info:
  version: 1.0.0
  title: Vaccinated API
  description: A sample vaccinated API
servers:
  - url: http://localhost:3000
paths:
  /person:
    get:
      description: Returns a list of all people
      responses:
        '200':
          description: List of people returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Person'
    
  /person/vaccinated:
    get:
      description: Returns only the vaccinated people
      responses:
        '200':
          description: Person data returned successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
  /person/count:
    get:
      description: Returns the number of vaccinated people
      responses:
        '200':
          description: Vaccinated count data returned successfully
          content:
            application/json:
              schema:
                type: integer
components:
  schemas:
    Person:
      type: object
      required:
        - id
        - firstName
        - lastName
        - vaccine
      properties:
        id:
          type: integer
        firstName:
          type: string
        lastName:
          type: string
        vaccine:
          type: string
